[Definition]
failregex = ^FAIL2BAN reason=BLINDBOX_AUTH_FAIL .* remote_host=<HOST>(?:\s|$)
            ^FAIL2BAN reason=BLINDBOX_HTTP_AUTH_FAIL .* remote_host=<HOST>(?:\s|$)
            ^FAIL2BAN reason=BLINDBOX_RATE_LIMIT .* remote_host=<HOST>(?:\s|$)
ignoreregex =

[Init]
datepattern = ^ts=%%s
