name: Nix Flake Check

on:
  push:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - '**.py'
  pull_request:
    paths:
      - 'flake.nix'
      - 'flake.lock'
      - '**.py'
  workflow_dispatch:

permissions:
  contents: read

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27

      - name: Check flake and build
        run: nix flake check --print-build-logs
